#pragma config(Sensor, S3, HTIRL, sensorI2CCustom)
#pragma config(Sensor, S2, , sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "HS485Connect.h"
#include "hitechnic-irlink.h"

byte irport = 2;
const byte forward = 7;
const byte backward = 10;
void send()
{
    while (iRezult != 138) {
        nxtDisplayBigTextLine(0, "%d", iRezult);
        Transmit(139);
        wait1Msec(15);
    }
}

void waitStart()
{
    while (SensorValue[S2] > 10 && SensorValue[S2] < 200)
        wait1Msec(10);
    PlaySound(soundBeepBeep);
    wait1Msec(1000);
    send();
}

void startMotor(int speed)
{
    PFMotor(pfmotor_S3_C2_A, (ePWMMotorCommand)speed);
    PFMotor(pfmotor_S3_C2_B, (ePWMMotorCommand)speed);
    wait1Msec(10);
}

void stopMotors()
{
    PFcomboDirectMode(HTIRL, irport - 1, CDM_MOTOR_BRAKE, CDM_MOTOR_BRAKE);
    wait1Msec(10);
}

task main()
{
    setupHighSpeedLink();
    wait1Msec(1000);
    waitStart();
    time1[0] = 0;
    while (true) {
        motor[motorA] = 100;
        motor[motorB] = 100;
        motor[motorC] = 100;
        if (time1[0] > 25000 && time1[0] < 60000) {
            startMotor(backward);
        }
        if (time1[0] > 60000) {
            stopMotors();
        }
        nxtDisplayBigTextLine(0, "%d", time1[0]);
        wait1Msec(10);
    }
}
