#pragma config(Sensor, S2,     ,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "HS485Connect.h"
void send()
{
	while (iRezult != 138)
	{
		nxtDisplayBigTextLine(0, "%d", iRezult);
		Transmit(139);
		wait1Msec(15);
	}
}

void waitStart()
{
	while (SensorValue[S2] > 10 && SensorValue[S2] < 200)
		wait1Msec(10);
	PlaySound(soundBeepBeep);
	wait1Msec(1000);
	send();
}
task main()
{
	setupHighSpeedLink();
	wait1Msec(1000);
	waitStart();
	while (true)
	{
		motor[motorA]=100;
		motor[motorB]=100;
		motor[motorC]=100;
	}
}
